using CrazyPawn;
using UnityEngine;
using Zenject;

namespace Services
{
    //Generated by AI
    public class BoardGenerator
    {
        [Inject] private CrazyPawnSettings _crazyPawnSettings;

        private const float CellSize = 1.5f;

        public void Generate(Vector3 position)
        {
            var cellsCount = _crazyPawnSettings.CheckerboardSize;
            var startPoint = cellsCount / 2f * CellSize - (CellSize / 2f);
            var startPosition = new Vector3(-startPoint, 0f, -startPoint);
            var blackColor = _crazyPawnSettings.BlackCellColor;
            var whiteColor = _crazyPawnSettings.WhiteCellColor;
            
            for (var x = 0; x < cellsCount; x++)
            {
                for (var z = 0; z < cellsCount; z++)
                {
                    var cellPosition = startPosition + new Vector3(x * CellSize, 0, z * CellSize);
                    var cellColor = (x + z) % 2 == 0 ? blackColor : whiteColor;
                    CreateCell(cellPosition, cellColor);
                }
            }
        }

        private void CreateCell(Vector3 position, Color color)
        {
            var cell = GameObject.CreatePrimitive(PrimitiveType.Plane);
            cell.transform.position = position;
            cell.transform.localScale = new Vector3(CellSize / 10, 1, CellSize / 10); // Plane по умолчанию 10x10
            
            var renderer = cell.GetComponent<Renderer>();
            
            if (renderer != null)
            {
                renderer.material.color = color;
            }
        }
    }
}