using UnityEngine;

namespace Core.Prank
{
    public class PrankLine: MonoBehaviour
    {
        private GameObject _gameObject;
        private Transform _transform;
        private float _timer = 5f;

        //Generated by AI
        public void Init(LineRenderer lineRenderer)
        {
            _gameObject = gameObject;
            
            if (lineRenderer.positionCount < 2)
            {
                Debug.LogError("LineRenderer должен иметь минимум 2 точки!");
                return;
            }

            var lineWidth = lineRenderer.widthMultiplier;
            var startPoint = lineRenderer.GetPosition(0);
            var endPoint = lineRenderer.GetPosition(lineRenderer.positionCount - 1);

            var direction = endPoint - startPoint;
            var length = direction.magnitude;
            var position = (startPoint + endPoint) / 2f;
            var rotation = Quaternion.LookRotation(direction) * Quaternion.Euler(90f, 0f, 0f);

            _transform = _gameObject.transform;
            _transform.position = position;
            _transform.rotation = rotation;
            _transform.localScale = new Vector3(lineWidth,length /2f ,lineWidth); 

            var cylinderCollider = _gameObject.GetComponent<CapsuleCollider>();
            cylinderCollider.center = Vector3.zero;
            cylinderCollider.radius = lineWidth * 5;
        }
        
        //Not optimized, just for fun
        private void Update()
        {
            _timer -= Time.deltaTime;

            if (_timer <= 0f) Destroy(gameObject);
        }
    }
}